// Placeholder for Shadcn/UI Toaster component
// This would normally be generated by shadcn/ui CLI

export function Toaster() {
  return (
    <div id="toast-container" className="fixed bottom-0 right-0 p-4 space-y-2 z-50">
      {/* Toast notifications will be rendered here */}
    </div>
  );
}